// Generated by: https://www.figma.com/community/plugin/842128343887142055/
import 'package:flutter/material.dart';

class FigmaToCodeApp extends StatelessWidget {
  const FigmaToCodeApp({super.key});

  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      theme: ThemeData.dark().copyWith(
        scaffoldBackgroundColor: const Color.fromARGB(255, 18, 32, 47),
      ),
      home: Scaffold(
        body: ListView(children: const [
          LoginScreen(),
        ]),
      ),
    );
  }
}

class LoginScreen extends StatefulWidget {
  const LoginScreen({super.key});
  @override
  State<LoginScreen> createState() => _LoginScreenState();
}

class _LoginScreenState extends State<LoginScreen> {
  final _formKey = GlobalKey<FormState>();
  String email = '', password = '';

  @override
  Widget build(BuildContext context) {
    return Container(
      width: 360,
      height: 800,
      clipBehavior: Clip.antiAlias,
      decoration: const BoxDecoration(color: Colors.white),
      child: Form(
        key: _formKey,
        child: Stack(
          children: [
            Positioned(
              left: 42,
              top: 337,
              child: Container(
                width: 277,
                height: 37.56,
                padding:
                    const EdgeInsets.symmetric(horizontal: 16, vertical: 10),
                decoration: ShapeDecoration(
                  color: const Color(0xFFF0F1F5),
                  shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(8)),
                ),
                child: Row(
                  mainAxisSize: MainAxisSize.min,
                  mainAxisAlignment: MainAxisAlignment.start,
                  crossAxisAlignment: CrossAxisAlignment.center,
                  children: [
                    TextFormField(
                      onChanged: (value) => email = value,
                      decoration: const InputDecoration(hintText: 'Username!!'),
                      style: const TextStyle(
                        color: Color(0xFF979CB5),
                        fontSize: 20,
                        fontFamily: 'Open Sans',
                        fontWeight: FontWeight.w600,
                        height: 0,
                      ),
                    ),
                  ],
                ),
              ),
            ),
            Positioned(
              left: 42,
              top: 387,
              child: Container(
                width: 277,
                height: 37.56,
                padding:
                    const EdgeInsets.symmetric(horizontal: 16, vertical: 10),
                decoration: ShapeDecoration(
                  color: const Color(0xFFF0F1F5),
                  shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(8)),
                ),
                child: Row(
                  mainAxisSize: MainAxisSize.min,
                  mainAxisAlignment: MainAxisAlignment.start,
                  crossAxisAlignment: CrossAxisAlignment.center,
                  children: [
                    TextFormField(
                      onChanged: (value) => password = value,
                      decoration: const InputDecoration(hintText: 'Password'),
                      style: const TextStyle(
                        color: Color(0xFF979CB5),
                        fontSize: 20,
                        fontFamily: 'Open Sans',
                        fontWeight: FontWeight.w600,
                        height: 0,
                      ),
                    ),
                  ],
                ),
              ),
            ),
            const Positioned(
              left: 121,
              top: 272,
              child: SizedBox(
                width: 107,
                height: 36,
                child: Text(
                  'SPLITiT',
                  style: TextStyle(
                    color: Colors.black,
                    fontSize: 30,
                    fontStyle: FontStyle.italic,
                    fontFamily: 'Open Sans',
                    fontWeight: FontWeight.w700,
                    height: 0,
                  ),
                ),
              ),
            ),
            Positioned(
              left: 121,
              top: 215,
              child: SizedBox(
                width: 71.93,
                height: 54.41,
                child: Stack(
                  children: [
                    const Positioned(
                      left: 0,
                      top: 0,
                      child: SizedBox(
                        width: 57.38,
                        height: 54.41,
                        child: Stack(children: []),
                      ),
                    ),
                    Positioned(
                      left: 36.40,
                      top: 7.12,
                      child: Transform(
                        transform: Matrix4.identity()
                          ..translate(0.0, 0.0)
                          ..rotateZ(0.13),
                        child: Container(
                          width: 35.82,
                          height: 35.82,
                          decoration: const ShapeDecoration(
                            color: Color(0xFFF9F471),
                            shape: OvalBorder(
                              side: BorderSide(color: Color(0xFF25B545)),
                            ),
                          ),
                        ),
                      ),
                    ),
                  ],
                ),
              ),
            ),
            Positioned(
              left: 162,
              top: 196,
              child: SizedBox(
                width: 96.39,
                height: 87.78,
                child: Stack(
                  children: [
                    const Positioned(
                      left: 7.25,
                      top: 10.88,
                      child: SizedBox(
                        width: 57.38,
                        height: 54.41,
                        child: Stack(children: []),
                      ),
                    ),
                    Positioned(
                      left: 0,
                      top: 0,
                      child: SizedBox(
                        width: 96.39,
                        height: 87.78,
                        child: Stack(
                          children: [
                            Positioned(
                              left: 17.21,
                              top: 0,
                              child: Container(
                                width: 79.18,
                                height: 5.16,
                                decoration: const BoxDecoration(
                                    color: Color(0xFFD9D9D9)),
                              ),
                            ),
                            Positioned(
                              left: 10.33,
                              top: 20.66,
                              child: Container(
                                width: 79.18,
                                height: 5.16,
                                decoration: const BoxDecoration(
                                    color: Color(0xFFD9D9D9)),
                              ),
                            ),
                            Positioned(
                              left: 10.33,
                              top: 30.98,
                              child: Container(
                                width: 79.18,
                                height: 5.16,
                                decoration: const BoxDecoration(
                                    color: Color(0xFFD9D9D9)),
                              ),
                            ),
                            Positioned(
                              left: 6.89,
                              top: 41.31,
                              child: Container(
                                width: 79.18,
                                height: 5.16,
                                decoration: const BoxDecoration(
                                    color: Color(0xFFD9D9D9)),
                              ),
                            ),
                            Positioned(
                              left: 6.89,
                              top: 51.64,
                              child: Container(
                                width: 79.18,
                                height: 5.16,
                                decoration: const BoxDecoration(
                                    color: Color(0xFFD9D9D9)),
                              ),
                            ),
                            Positioned(
                              left: 3.44,
                              top: 61.97,
                              child: Container(
                                width: 79.18,
                                height: 5.16,
                                decoration: const BoxDecoration(
                                    color: Color(0xFFD9D9D9)),
                              ),
                            ),
                            Positioned(
                              left: 0,
                              top: 72.29,
                              child: Container(
                                width: 79.18,
                                height: 5.16,
                                decoration: const BoxDecoration(
                                    color: Color(0xFFD9D9D9)),
                              ),
                            ),
                            Positioned(
                              left: 0,
                              top: 82.62,
                              child: Container(
                                width: 79.18,
                                height: 5.16,
                                decoration: const BoxDecoration(
                                    color: Color(0xFFD9D9D9)),
                              ),
                            ),
                          ],
                        ),
                      ),
                    ),
                  ],
                ),
              ),
            ),
            Positioned(
              left: 42,
              top: 337,
              child: Container(
                width: 277,
                height: 37.56,
                padding:
                    const EdgeInsets.symmetric(horizontal: 16, vertical: 10),
                decoration: ShapeDecoration(
                  color: const Color(0xFFF0F1F5),
                  shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(8)),
                ),
                child: const Row(
                  mainAxisSize: MainAxisSize.min,
                  mainAxisAlignment: MainAxisAlignment.start,
                  crossAxisAlignment: CrossAxisAlignment.center,
                  children: [
                    Text(
                      'Username???',
                      style: TextStyle(
                        color: Color(0xFF979CB5),
                        fontSize: 15,
                        fontFamily: 'Open Sans',
                        fontWeight: FontWeight.w600,
                        height: 0,
                      ),
                    ),
                  ],
                ),
              ),
            ),
            Positioned(
              left: 42,
              top: 387,
              child: Container(
                width: 277,
                height: 37.56,
                padding:
                    const EdgeInsets.symmetric(horizontal: 16, vertical: 10),
                decoration: ShapeDecoration(
                  color: const Color(0xFFF0F1F5),
                  shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(8)),
                ),
                child: Row(
                  mainAxisSize: MainAxisSize.min,
                  mainAxisAlignment: MainAxisAlignment.start,
                  crossAxisAlignment: CrossAxisAlignment.center,
                  children: [
                    TextFormField(
                      onChanged: (value) => password = value,
                      decoration: const InputDecoration(hintText: 'Password'),
                      style: const TextStyle(
                        color: Color(0xFF979CB5),
                        fontSize: 15,
                        fontFamily: 'Open Sans',
                        fontWeight: FontWeight.w600,
                        height: 0,
                      ),
                    ),
                  ],
                ),
              ),
            ),
            Positioned(
              left: 121,
              top: 555.95,
              child: SizedBox(
                width: 117.02,
                height: 24,
                child: Stack(
                  children: [
                    Positioned(
                      left: 0,
                      top: 0,
                      child: Container(
                        width: 24,
                        height: 24,
                        clipBehavior: Clip.antiAlias,
                        decoration: const BoxDecoration(),
                        child: const Column(
                          mainAxisSize: MainAxisSize.min,
                          mainAxisAlignment: MainAxisAlignment.start,
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: [],
                        ),
                      ),
                    ),
                    Positioned(
                      left: 46.50,
                      top: -0.38,
                      child: Container(
                        width: 24,
                        height: 24,
                        clipBehavior: Clip.antiAlias,
                        decoration: const BoxDecoration(),
                        child: const Column(
                          mainAxisSize: MainAxisSize.min,
                          mainAxisAlignment: MainAxisAlignment.start,
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: [],
                        ),
                      ),
                    ),
                    Positioned(
                      left: 93.01,
                      top: -0.76,
                      child: Container(
                        width: 24,
                        height: 24,
                        clipBehavior: Clip.antiAlias,
                        decoration: const BoxDecoration(),
                        child: const Column(
                          mainAxisSize: MainAxisSize.min,
                          mainAxisAlignment: MainAxisAlignment.start,
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: [],
                        ),
                      ),
                    ),
                  ],
                ),
              ),
            ),
            const Positioned(
              left: 121,
              top: 272,
              child: SizedBox(
                width: 107,
                height: 36,
                child: Text(
                  'SPLITiT',
                  style: TextStyle(
                    color: Colors.black,
                    fontSize: 30,
                    fontStyle: FontStyle.italic,
                    fontFamily: 'Open Sans',
                    fontWeight: FontWeight.w700,
                    height: 0,
                  ),
                ),
              ),
            ),
            Positioned(
              left: 42,
              top: 441,
              child: Container(
                width: 277,
                height: 40,
                padding:
                    const EdgeInsets.symmetric(horizontal: 16, vertical: 10),
                decoration: ShapeDecoration(
                  color: const Color(0xFF25B545),
                  shape: RoundedRectangleBorder(
                      borderRadius: BorderRadius.circular(8)),
                ),
                child: Row(
                  mainAxisSize: MainAxisSize.min,
                  mainAxisAlignment: MainAxisAlignment.center,
                  crossAxisAlignment: CrossAxisAlignment.center,
                  children: [
                    ElevatedButton(
                      style: ElevatedButton.styleFrom(
                          minimumSize: const Size.fromWidth(218)),
                      onPressed: () {},
                      child: const Text(
                        'Login',
                        textAlign: TextAlign.center,
                        style: TextStyle(
                          color: Colors.white,
                          fontSize: 16,
                          fontFamily: 'Open Sans',
                          fontWeight: FontWeight.w600,
                          height: 0,
                        ),
                      ),
                    ),
                  ],
                ),
              ),
            ),
            const Positioned(
              left: 104,
              top: 780,
              child: SizedBox(
                width: 161,
                height: 9,
                child: Text.rich(
                  TextSpan(
                    children: [
                      TextSpan(
                        text: 'Dont have an account?',
                        style: TextStyle(
                          color: Color(0xFFF0F1F5),
                          fontSize: 10,
                          fontFamily: 'Open Sans',
                          fontWeight: FontWeight.w600,
                          height: 0,
                        ),
                      ),
                      TextSpan(
                        text: '  ',
                        style: TextStyle(
                          color: Color(0xFF979CB5),
                          fontSize: 10,
                          fontFamily: 'Open Sans',
                          fontWeight: FontWeight.w600,
                          height: 0,
                        ),
                      ),
                      TextSpan(
                        text: 'Sign Up',
                        style: TextStyle(
                          color: Color(0xFF368147),
                          fontSize: 10,
                          fontFamily: 'Open Sans',
                          fontWeight: FontWeight.w600,
                          height: 0,
                        ),
                      ),
                    ],
                  ),
                  textAlign: TextAlign.center,
                ),
              ),
            ),
            const Positioned(
              left: 235,
              top: 493,
              child: SizedBox(
                width: 84,
                height: 9,
                child: Text(
                  'forgot password?',
                  textAlign: TextAlign.center,
                  style: TextStyle(
                    color: Color(0xFF979CB5),
                    fontSize: 10,
                    fontFamily: 'Open Sans',
                    fontWeight: FontWeight.w600,
                    height: 0,
                  ),
                ),
              ),
            ),
            const Positioned(
              left: 150,
              top: 532,
              child: SizedBox(
                width: 61,
                height: 9,
                child: Text(
                  'or login with',
                  textAlign: TextAlign.center,
                  style: TextStyle(
                    color: Color(0xFF979CB5),
                    fontSize: 10,
                    fontFamily: 'Open Sans',
                    fontWeight: FontWeight.w600,
                    height: 0,
                  ),
                ),
              ),
            ),
          ],
        ),
      ),
    );
  }
}
