@startuml Bill

class "project_bs::net_models::bill::bill_data_dto.dart::BillDataDTO" {
    +BillData toRuntimeObj()
}

' "project_bs::net_models::bill::bill_data_dto.dart::_$BillDataDTO" <|-- "project_bs::net_models::bill::bill_data_dto.dart::BillDataDTO"

' abstract class "project_bs::net_models::bill::bill_data_dto.dart::$BillDataDTOCopyWith" {
'     +$Res call()
' }

' class "project_bs::net_models::bill::bill_data_dto.dart::_$BillDataDTOCopyWithImpl" {
'     -$Val _value
'     -$Res Function($Val) _then
'     +$Res call()
' }

' "project_bs::net_models::bill::bill_data_dto.dart::_$BillDataDTOCopyWithImpl" o-- "null::$Res Function($Val)"
' "project_bs::net_models::bill::bill_data_dto.dart::$BillDataDTOCopyWith" <|-- "project_bs::net_models::bill::bill_data_dto.dart::_$BillDataDTOCopyWithImpl"

' abstract class "project_bs::net_models::bill::bill_data_dto.dart::_$$BillDataDTOImplCopyWith" {
'     +$Res call()
' }

' "project_bs::net_models::bill::bill_data_dto.dart::$BillDataDTOCopyWith" <|-- "project_bs::net_models::bill::bill_data_dto.dart::_$$BillDataDTOImplCopyWith"

' class "project_bs::net_models::bill::bill_data_dto.dart::__$$BillDataDTOImplCopyWithImpl" {
'     +$Res call()
' }

' "project_bs::net_models::bill::bill_data_dto.dart::_$BillDataDTOCopyWithImpl" <|-- "project_bs::net_models::bill::bill_data_dto.dart::__$$BillDataDTOImplCopyWithImpl"
' "project_bs::net_models::bill::bill_data_dto.dart::_$$BillDataDTOImplCopyWith" <|-- "project_bs::net_models::bill::bill_data_dto.dart::__$$BillDataDTOImplCopyWithImpl"

' class "project_bs::net_models::bill::bill_data_dto.dart::_$BillDataDTOImpl" {
'     +DateTime dateTime
'     +String name
'     +double totalSpent
'     +String payerUid
'     -List<String> _primarySplits
'     -Map<String, double> _splitBalances
'     -Map<String, double> _paymentResolveStatuses
'     +DateTime lastUpdatedSession
'     +List<String> primarySplits
'     +Map<String, double> splitBalances
'     +Map<String, double> paymentResolveStatuses
'     +int hashCode
'     +_$$BillDataDTOImplCopyWith<_$BillDataDTOImpl> copyWith
'     +String toString()
'     +bool ==()
'     +Map<String, dynamic> toJson()
' }

' "project_bs::net_models::bill::bill_data_dto.dart::_$BillDataDTOImpl" o-- "project_bs::net_models::bill::bill_data_dto.dart::_$$BillDataDTOImplCopyWith<_$BillDataDTOImpl>"
' "project_bs::net_models::bill::bill_data_dto.dart::_BillDataDTO" <|-- "project_bs::net_models::bill::bill_data_dto.dart::_$BillDataDTOImpl"

abstract class "project_bs::net_models::bill::bill_data_dto.dart::_BillDataDTO" {
    +DateTime dateTime
    +String name
    +double totalSpent
    +String payerUid
    +List<String> primarySplits
    +Map<String, double> splitBalances
    +Map<String, double> paymentResolveStatuses
    +DateTime lastUpdatedSession
    ' +_$$BillDataDTOImplCopyWith<_$BillDataDTOImpl> copyWith
}

' "project_bs::net_models::bill::bill_data_dto.dart::_BillDataDTO" o-- "project_bs::net_models::bill::bill_data_dto.dart::_$$BillDataDTOImplCopyWith<_$BillDataDTOImpl>"
"project_bs::net_models::bill::bill_data_dto.dart::BillDataDTO" <|-- "project_bs::net_models::bill::bill_data_dto.dart::_BillDataDTO"

' abstract class "project_bs::net_models::bill::bill_data_dto.dart::_$BillDataDTO" {
'     +DateTime dateTime
'     +String name
'     +double totalSpent
'     +String payerUid
'     +List<String> primarySplits
'     +Map<String, double> splitBalances
'     +Map<String, double> paymentResolveStatuses
'     +DateTime lastUpdatedSession
'     +$BillDataDTOCopyWith<BillDataDTO> copyWith
'     +Map<String, dynamic> toJson()
' }

' "project_bs::net_models::bill::bill_data_dto.dart::_$BillDataDTO" o-- "project_bs::net_models::bill::bill_data_dto.dart::$BillDataDTOCopyWith<BillDataDTO>"




class "project_bs::runtime_models::bill::bill_data.dart::BillData" {
    +BillDataDTO toDataTransferObj
    +ItemGroup everythingElseItemGroup
    +double everythingElse
}

"project_bs::runtime_models::bill::bill_data.dart::BillData" o-- "project_bs::net_models::bill::bill_data_dto.dart::BillDataDTO"
"project_bs::runtime_models::bill::bill_data.dart::BillData" o-- "project_bs::runtime_models::bill::item_group.dart::ItemGroup"
' "project_bs::runtime_models::bill::bill_data.dart::_$BillData" <|-- "project_bs::runtime_models::bill::bill_data.dart::BillData"

' abstract class "project_bs::runtime_models::bill::bill_data.dart::$BillDataCopyWith" {
'     +$PublicProfileCopyWith<$Res>? payer
'     +$BillModule_TaxCopyWith<$Res> taxModule
'     +$BillModule_TipCopyWith<$Res> tipModule
'     +$Res call()
' }

' "project_bs::runtime_models::bill::bill_data.dart::$BillDataCopyWith" o-- "project_bs::runtime_models::user::public_profile.dart::$PublicProfileCopyWith<$Res>"
' "project_bs::runtime_models::bill::bill_data.dart::$BillDataCopyWith" o-- "project_bs::runtime_models::bill::modules::bill_module_tax.dart::$BillModule_TaxCopyWith<$Res>"
' "project_bs::runtime_models::bill::bill_data.dart::$BillDataCopyWith" o-- "project_bs::runtime_models::bill::modules::bill_module_tip.dart::$BillModule_TipCopyWith<$Res>"

' class "project_bs::runtime_models::bill::bill_data.dart::_$BillDataCopyWithImpl" {
'     -$Val _value
'     -$Res Function($Val) _then
'     +$PublicProfileCopyWith<$Res>? payer
'     +$BillModule_TaxCopyWith<$Res> taxModule
'     +$BillModule_TipCopyWith<$Res> tipModule
'     +$Res call()
' }

' "project_bs::runtime_models::bill::bill_data.dart::_$BillDataCopyWithImpl" o-- "null::$Res Function($Val)"
' "project_bs::runtime_models::bill::bill_data.dart::_$BillDataCopyWithImpl" o-- "project_bs::runtime_models::user::public_profile.dart::$PublicProfileCopyWith<$Res>"
' "project_bs::runtime_models::bill::bill_data.dart::_$BillDataCopyWithImpl" o-- "project_bs::runtime_models::bill::modules::bill_module_tax.dart::$BillModule_TaxCopyWith<$Res>"
' "project_bs::runtime_models::bill::bill_data.dart::_$BillDataCopyWithImpl" o-- "project_bs::runtime_models::bill::modules::bill_module_tip.dart::$BillModule_TipCopyWith<$Res>"
' "project_bs::runtime_models::bill::bill_data.dart::$BillDataCopyWith" <|-- "project_bs::runtime_models::bill::bill_data.dart::_$BillDataCopyWithImpl"

' abstract class "project_bs::runtime_models::bill::bill_data.dart::_$$BillDataImplCopyWith" {
'     +$PublicProfileCopyWith<$Res>? payer
'     +$BillModule_TaxCopyWith<$Res> taxModule
'     +$BillModule_TipCopyWith<$Res> tipModule
'     +$Res call()
' }

' "project_bs::runtime_models::bill::bill_data.dart::_$$BillDataImplCopyWith" o-- "project_bs::runtime_models::user::public_profile.dart::$PublicProfileCopyWith<$Res>"
' "project_bs::runtime_models::bill::bill_data.dart::_$$BillDataImplCopyWith" o-- "project_bs::runtime_models::bill::modules::bill_module_tax.dart::$BillModule_TaxCopyWith<$Res>"
' "project_bs::runtime_models::bill::bill_data.dart::_$$BillDataImplCopyWith" o-- "project_bs::runtime_models::bill::modules::bill_module_tip.dart::$BillModule_TipCopyWith<$Res>"
' "project_bs::runtime_models::bill::bill_data.dart::$BillDataCopyWith" <|-- "project_bs::runtime_models::bill::bill_data.dart::_$$BillDataImplCopyWith"

' class "project_bs::runtime_models::bill::bill_data.dart::__$$BillDataImplCopyWithImpl" {
'     +$Res call()
' }

' "project_bs::runtime_models::bill::bill_data.dart::_$BillDataCopyWithImpl" <|-- "project_bs::runtime_models::bill::bill_data.dart::__$$BillDataImplCopyWithImpl"
' "project_bs::runtime_models::bill::bill_data.dart::_$$BillDataImplCopyWith" <|-- "project_bs::runtime_models::bill::bill_data.dart::__$$BillDataImplCopyWithImpl"

' class "project_bs::runtime_models::bill::bill_data.dart::_$BillDataImpl" {
'     +String uid
'     +DateTime dateTime
'     +String name
'     +double totalSpent
'     +PublicProfile? payer
'     +List<PublicProfile> primarySplits
'     +List<PublicProfile>? secondarySplits
'     +Map<PublicProfile, double> splitBalances
'     +Map<PublicProfile, double> paymentResolveStatuses
'     +List<ItemGroup> itemGroups
'     +BillModule_Tax taxModule
'     +BillModule_Tip tipModule
'     +DateTime lastUpdatedSession
'     +_$$BillDataImplCopyWith<_$BillDataImpl> copyWith
'     +String toString()
' }

' "project_bs::runtime_models::bill::bill_data.dart::_$BillDataImpl" o-- "project_bs::runtime_models::user::public_profile.dart::PublicProfile"
' "project_bs::runtime_models::bill::bill_data.dart::_$BillDataImpl" o-- "project_bs::runtime_models::bill::modules::bill_module_tax.dart::BillModule_Tax"
' "project_bs::runtime_models::bill::bill_data.dart::_$BillDataImpl" o-- "project_bs::runtime_models::bill::modules::bill_module_tip.dart::BillModule_Tip"
' "project_bs::runtime_models::bill::bill_data.dart::_$BillDataImpl" o-- "project_bs::runtime_models::bill::bill_data.dart::_$$BillDataImplCopyWith<_$BillDataImpl>"
' "project_bs::runtime_models::bill::bill_data.dart::_BillData" <|-- "project_bs::runtime_models::bill::bill_data.dart::_$BillDataImpl"

abstract class "project_bs::runtime_models::bill::bill_data.dart::_BillData" {
    +String uid
    +DateTime dateTime
    +String name
    +double totalSpent
    +PublicProfile? payer
    +List<PublicProfile> primarySplits
    +List<PublicProfile>? secondarySplits
    +Map<PublicProfile, double> splitBalances
    +Map<PublicProfile, double> paymentResolveStatuses
    +List<ItemGroup> itemGroups
    +BillModule_Tax taxModule
    +BillModule_Tip tipModule
    +DateTime lastUpdatedSession
    ' +_$$BillDataImplCopyWith<_$BillDataImpl> copyWith
}

"project_bs::runtime_models::bill::bill_data.dart::_BillData" o-- "project_bs::runtime_models::user::public_profile.dart::PublicProfile"
"project_bs::runtime_models::bill::bill_data.dart::_BillData" o-- "project_bs::runtime_models::bill::modules::bill_module_tax.dart::BillModule_Tax"
"project_bs::runtime_models::bill::bill_data.dart::_BillData" o-- "project_bs::runtime_models::bill::modules::bill_module_tip.dart::BillModule_Tip"
' "project_bs::runtime_models::bill::bill_data.dart::_BillData" o-- "project_bs::runtime_models::bill::bill_data.dart::_$$BillDataImplCopyWith<_$BillDataImpl>"
"project_bs::runtime_models::bill::bill_data.dart::BillData" <|-- "project_bs::runtime_models::bill::bill_data.dart::_BillData"

' abstract class "project_bs::runtime_models::bill::bill_data.dart::_$BillData" {
'     +String uid
'     +DateTime dateTime
'     +String name
'     +double totalSpent
'     +PublicProfile? payer
'     +List<PublicProfile> primarySplits
'     +List<PublicProfile>? secondarySplits
'     +Map<PublicProfile, double> splitBalances
'     +Map<PublicProfile, double> paymentResolveStatuses
'     +List<ItemGroup> itemGroups
'     +BillModule_Tax taxModule
'     +BillModule_Tip tipModule
'     +DateTime lastUpdatedSession
'     +$BillDataCopyWith<BillData> copyWith
' }

' "project_bs::runtime_models::bill::bill_data.dart::_$BillData" o-- "project_bs::runtime_models::user::public_profile.dart::PublicProfile"
' "project_bs::runtime_models::bill::bill_data.dart::_$BillData" o-- "project_bs::runtime_models::bill::modules::bill_module_tax.dart::BillModule_Tax"
' "project_bs::runtime_models::bill::bill_data.dart::_$BillData" o-- "project_bs::runtime_models::bill::modules::bill_module_tip.dart::BillModule_Tip"
' "project_bs::runtime_models::bill::bill_data.dart::_$BillData" o-- "project_bs::runtime_models::bill::bill_data.dart::$BillDataCopyWith<BillData>"

class "project_bs::runtime_models::bill::item.dart::Item" {
}

' "project_bs::runtime_models::bill::item.dart::_$Item" <|-- "project_bs::runtime_models::bill::item.dart::Item"

' abstract class "project_bs::runtime_models::bill::item.dart::$ItemCopyWith" {
'     +$Res call()
' }

' class "project_bs::runtime_models::bill::item.dart::_$ItemCopyWithImpl" {
'     -$Val _value
'     -$Res Function($Val) _then
'     +$Res call()
' }

' "project_bs::runtime_models::bill::item.dart::_$ItemCopyWithImpl" o-- "null::$Res Function($Val)"
' "project_bs::runtime_models::bill::item.dart::$ItemCopyWith" <|-- "project_bs::runtime_models::bill::item.dart::_$ItemCopyWithImpl"

' abstract class "project_bs::runtime_models::bill::item.dart::_$$ItemImplCopyWith" {
'     +$Res call()
' }

' "project_bs::runtime_models::bill::item.dart::$ItemCopyWith" <|-- "project_bs::runtime_models::bill::item.dart::_$$ItemImplCopyWith"

' class "project_bs::runtime_models::bill::item.dart::__$$ItemImplCopyWithImpl" {
'     +$Res call()
' }

' "project_bs::runtime_models::bill::item.dart::_$ItemCopyWithImpl" <|-- "project_bs::runtime_models::bill::item.dart::__$$ItemImplCopyWithImpl"
' "project_bs::runtime_models::bill::item.dart::_$$ItemImplCopyWith" <|-- "project_bs::runtime_models::bill::item.dart::__$$ItemImplCopyWithImpl"

' class "project_bs::runtime_models::bill::item.dart::_$ItemImpl" {
'     +String name
'     +double value
'     -List<bool> _taxableStatusList
'     +List<bool> taxableStatusList
'     +int hashCode
'     +_$$ItemImplCopyWith<_$ItemImpl> copyWith
'     +String toString()
'     +bool ==()
' }

' "project_bs::runtime_models::bill::item.dart::_$ItemImpl" o-- "project_bs::runtime_models::bill::item.dart::_$$ItemImplCopyWith<_$ItemImpl>"
' "project_bs::runtime_models::bill::item.dart::_Item" <|-- "project_bs::runtime_models::bill::item.dart::_$ItemImpl"

abstract class "project_bs::runtime_models::bill::item.dart::_Item" {
    +String name
    +double value
    +List<bool> taxableStatusList
    ' +_$$ItemImplCopyWith<_$ItemImpl> copyWith
}

' "project_bs::runtime_models::bill::item.dart::_Item" o-- "project_bs::runtime_models::bill::item.dart::_$$ItemImplCopyWith<_$ItemImpl>"
"project_bs::runtime_models::bill::item.dart::Item" <|-- "project_bs::runtime_models::bill::item.dart::_Item"

' abstract class "project_bs::runtime_models::bill::item.dart::_$Item" {
'     +String name
'     +double value
'     +List<bool> taxableStatusList
'     +$ItemCopyWith<Item> copyWith
' }

' "project_bs::runtime_models::bill::item.dart::_$Item" o-- "project_bs::runtime_models::bill::item.dart::$ItemCopyWith<Item>"

class "project_bs::runtime_models::bill::item_group.dart::ItemGroup" {
    +double value
}

' "project_bs::runtime_models::bill::item_group.dart::_$ItemGroup" <|-- "project_bs::runtime_models::bill::item_group.dart::ItemGroup"

' abstract class "project_bs::runtime_models::bill::item_group.dart::$ItemGroupCopyWith" {
'     +$Res call()
' }

' class "project_bs::runtime_models::bill::item_group.dart::_$ItemGroupCopyWithImpl" {
'     -$Val _value
'     -$Res Function($Val) _then
'     +$Res call()
' }

' "project_bs::runtime_models::bill::item_group.dart::_$ItemGroupCopyWithImpl" o-- "null::$Res Function($Val)"
' "project_bs::runtime_models::bill::item_group.dart::$ItemGroupCopyWith" <|-- "project_bs::runtime_models::bill::item_group.dart::_$ItemGroupCopyWithImpl"

' abstract class "project_bs::runtime_models::bill::item_group.dart::_$$ItemGroupImplCopyWith" {
'     +$Res call()
' }

' "project_bs::runtime_models::bill::item_group.dart::$ItemGroupCopyWith" <|-- "project_bs::runtime_models::bill::item_group.dart::_$$ItemGroupImplCopyWith"

' class "project_bs::runtime_models::bill::item_group.dart::__$$ItemGroupImplCopyWithImpl" {
'     +$Res call()
' }

' "project_bs::runtime_models::bill::item_group.dart::_$ItemGroupCopyWithImpl" <|-- "project_bs::runtime_models::bill::item_group.dart::__$$ItemGroupImplCopyWithImpl"
' "project_bs::runtime_models::bill::item_group.dart::_$$ItemGroupImplCopyWith" <|-- "project_bs::runtime_models::bill::item_group.dart::__$$ItemGroupImplCopyWithImpl"

' class "project_bs::runtime_models::bill::item_group.dart::_$ItemGroupImpl" {
'     +String name
'     -List<PublicProfile> _primarySplits
'     -List<Item> _items
'     -List<SplitRule> _splitRules
'     -Map<PublicProfile, double> _splitBalances
'     +List<PublicProfile> primarySplits
'     +List<Item> items
'     +List<SplitRule> splitRules
'     +Map<PublicProfile, double> splitBalances
'     +int hashCode
'     +_$$ItemGroupImplCopyWith<_$ItemGroupImpl> copyWith
'     +String toString()
'     +bool ==()
' }

' "project_bs::runtime_models::bill::item_group.dart::_$ItemGroupImpl" o-- "project_bs::runtime_models::bill::item_group.dart::_$$ItemGroupImplCopyWith<_$ItemGroupImpl>"
' "project_bs::runtime_models::bill::item_group.dart::_ItemGroup" <|-- "project_bs::runtime_models::bill::item_group.dart::_$ItemGroupImpl"

abstract class "project_bs::runtime_models::bill::item_group.dart::_ItemGroup" {
    +String name
    +List<PublicProfile> primarySplits
    +List<Item> items
    +List<SplitRule> splitRules
    +Map<PublicProfile, double> splitBalances
    ' +_$$ItemGroupImplCopyWith<_$ItemGroupImpl> copyWith
}

' "project_bs::runtime_models::bill::item_group.dart::_ItemGroup" o-- "project_bs::runtime_models::bill::item_group.dart::_$$ItemGroupImplCopyWith<_$ItemGroupImpl>"
"project_bs::runtime_models::bill::item_group.dart::ItemGroup" <|-- "project_bs::runtime_models::bill::item_group.dart::_ItemGroup"

' abstract class "project_bs::runtime_models::bill::item_group.dart::_$ItemGroup" {
'     +String name
'     +List<PublicProfile> primarySplits
'     +List<Item> items
'     +List<SplitRule> splitRules
'     +Map<PublicProfile, double> splitBalances
'     +$ItemGroupCopyWith<ItemGroup> copyWith
' }

' "project_bs::runtime_models::bill::item_group.dart::_$ItemGroup" o-- "project_bs::runtime_models::bill::item_group.dart::$ItemGroupCopyWith<ItemGroup>"

class "project_bs::runtime_models::bill::modules::bill_module_tax.dart::BillModule_Tax" {
}

' "project_bs::runtime_models::bill::modules::bill_module_tax.dart::_$BillModule_Tax" <|-- "project_bs::runtime_models::bill::modules::bill_module_tax.dart::BillModule_Tax"

' abstract class "project_bs::runtime_models::bill::modules::bill_module_tax.dart::$BillModule_TaxCopyWith" {
'     +$Res call()
' }

' class "project_bs::runtime_models::bill::modules::bill_module_tax.dart::_$BillModule_TaxCopyWithImpl" {
'     -$Val _value
'     -$Res Function($Val) _then
'     +$Res call()
' }

' "project_bs::runtime_models::bill::modules::bill_module_tax.dart::_$BillModule_TaxCopyWithImpl" o-- "null::$Res Function($Val)"
' "project_bs::runtime_models::bill::modules::bill_module_tax.dart::$BillModule_TaxCopyWith" <|-- "project_bs::runtime_models::bill::modules::bill_module_tax.dart::_$BillModule_TaxCopyWithImpl"

' abstract class "project_bs::runtime_models::bill::modules::bill_module_tax.dart::_$$BillModule_TaxImplCopyWith" {
'     +$Res call()
' }

' "project_bs::runtime_models::bill::modules::bill_module_tax.dart::$BillModule_TaxCopyWith" <|-- "project_bs::runtime_models::bill::modules::bill_module_tax.dart::_$$BillModule_TaxImplCopyWith"

' class "project_bs::runtime_models::bill::modules::bill_module_tax.dart::__$$BillModule_TaxImplCopyWithImpl" {
'     +$Res call()
' }

' "project_bs::runtime_models::bill::modules::bill_module_tax.dart::_$BillModule_TaxCopyWithImpl" <|-- "project_bs::runtime_models::bill::modules::bill_module_tax.dart::__$$BillModule_TaxImplCopyWithImpl"
' "project_bs::runtime_models::bill::modules::bill_module_tax.dart::_$$BillModule_TaxImplCopyWith" <|-- "project_bs::runtime_models::bill::modules::bill_module_tax.dart::__$$BillModule_TaxImplCopyWithImpl"

' class "project_bs::runtime_models::bill::modules::bill_module_tax.dart::_$BillModule_TaxImpl" {
'     +double totalTax
'     +int hashCode
'     +_$$BillModule_TaxImplCopyWith<_$BillModule_TaxImpl> copyWith
'     +String toString()
'     +bool ==()
' }

' "project_bs::runtime_models::bill::modules::bill_module_tax.dart::_$BillModule_TaxImpl" o-- "project_bs::runtime_models::bill::modules::bill_module_tax.dart::_$$BillModule_TaxImplCopyWith<_$BillModule_TaxImpl>"
' "project_bs::runtime_models::bill::modules::bill_module_tax.dart::_BillModule_Tax" <|-- "project_bs::runtime_models::bill::modules::bill_module_tax.dart::_$BillModule_TaxImpl"

abstract class "project_bs::runtime_models::bill::modules::bill_module_tax.dart::_BillModule_Tax" {
    +double totalTax
    ' +_$$BillModule_TaxImplCopyWith<_$BillModule_TaxImpl> copyWith
}

' "project_bs::runtime_models::bill::modules::bill_module_tax.dart::_BillModule_Tax" o-- "project_bs::runtime_models::bill::modules::bill_module_tax.dart::_$$BillModule_TaxImplCopyWith<_$BillModule_TaxImpl>"
"project_bs::runtime_models::bill::modules::bill_module_tax.dart::BillModule_Tax" <|-- "project_bs::runtime_models::bill::modules::bill_module_tax.dart::_BillModule_Tax"

' abstract class "project_bs::runtime_models::bill::modules::bill_module_tax.dart::_$BillModule_Tax" {
'     +double totalTax
'     +$BillModule_TaxCopyWith<BillModule_Tax> copyWith
' }

' "project_bs::runtime_models::bill::modules::bill_module_tax.dart::_$BillModule_Tax" o-- "project_bs::runtime_models::bill::modules::bill_module_tax.dart::$BillModule_TaxCopyWith<BillModule_Tax>"

class "project_bs::runtime_models::bill::modules::bill_module_tip.dart::BillModule_Tip" {
}

' "project_bs::runtime_models::bill::modules::bill_module_tip.dart::_$BillModule_Tip" <|-- "project_bs::runtime_models::bill::modules::bill_module_tip.dart::BillModule_Tip"

' abstract class "project_bs::runtime_models::bill::modules::bill_module_tip.dart::$BillModule_TipCopyWith" {
'     +$Res call()
' }

' class "project_bs::runtime_models::bill::modules::bill_module_tip.dart::_$BillModule_TipCopyWithImpl" {
'     -$Val _value
'     -$Res Function($Val) _then
'     +$Res call()
' }

' "project_bs::runtime_models::bill::modules::bill_module_tip.dart::_$BillModule_TipCopyWithImpl" o-- "null::$Res Function($Val)"
' "project_bs::runtime_models::bill::modules::bill_module_tip.dart::$BillModule_TipCopyWith" <|-- "project_bs::runtime_models::bill::modules::bill_module_tip.dart::_$BillModule_TipCopyWithImpl"

' abstract class "project_bs::runtime_models::bill::modules::bill_module_tip.dart::_$$BillModule_TipImplCopyWith" {
'     +$Res call()
' }

' "project_bs::runtime_models::bill::modules::bill_module_tip.dart::$BillModule_TipCopyWith" <|-- "project_bs::runtime_models::bill::modules::bill_module_tip.dart::_$$BillModule_TipImplCopyWith"

' class "project_bs::runtime_models::bill::modules::bill_module_tip.dart::__$$BillModule_TipImplCopyWithImpl" {
'     +$Res call()
' }

' "project_bs::runtime_models::bill::modules::bill_module_tip.dart::_$BillModule_TipCopyWithImpl" <|-- "project_bs::runtime_models::bill::modules::bill_module_tip.dart::__$$BillModule_TipImplCopyWithImpl"
' "project_bs::runtime_models::bill::modules::bill_module_tip.dart::_$$BillModule_TipImplCopyWith" <|-- "project_bs::runtime_models::bill::modules::bill_module_tip.dart::__$$BillModule_TipImplCopyWithImpl"

' class "project_bs::runtime_models::bill::modules::bill_module_tip.dart::_$BillModule_TipImpl" {
'     +double totalTip
'     +bool includedInTotalSpent
'     +int hashCode
'     +_$$BillModule_TipImplCopyWith<_$BillModule_TipImpl> copyWith
'     +String toString()
'     +bool ==()
' }

' "project_bs::runtime_models::bill::modules::bill_module_tip.dart::_$BillModule_TipImpl" o-- "project_bs::runtime_models::bill::modules::bill_module_tip.dart::_$$BillModule_TipImplCopyWith<_$BillModule_TipImpl>"
' "project_bs::runtime_models::bill::modules::bill_module_tip.dart::_BillModule_Tip" <|-- "project_bs::runtime_models::bill::modules::bill_module_tip.dart::_$BillModule_TipImpl"

abstract class "project_bs::runtime_models::bill::modules::bill_module_tip.dart::_BillModule_Tip" {
    +double totalTip
    +bool includedInTotalSpent
    ' +_$$BillModule_TipImplCopyWith<_$BillModule_TipImpl> copyWith
}

' "project_bs::runtime_models::bill::modules::bill_module_tip.dart::_BillModule_Tip" o-- "project_bs::runtime_models::bill::modules::bill_module_tip.dart::_$$BillModule_TipImplCopyWith<_$BillModule_TipImpl>"
"project_bs::runtime_models::bill::modules::bill_module_tip.dart::BillModule_Tip" <|-- "project_bs::runtime_models::bill::modules::bill_module_tip.dart::_BillModule_Tip"

' abstract class "project_bs::runtime_models::bill::modules::bill_module_tip.dart::_$BillModule_Tip" {
'     +double totalTip
'     +bool includedInTotalSpent
'     +$BillModule_TipCopyWith<BillModule_Tip> copyWith
' }

' "project_bs::runtime_models::bill::modules::bill_module_tip.dart::_$BillModule_Tip" o-- "project_bs::runtime_models::bill::modules::bill_module_tip.dart::$BillModule_TipCopyWith<BillModule_Tip>"

class "project_bs::runtime_models::bill::split_rules::split_rule.dart::SplitRule" {
}

' "project_bs::runtime_models::bill::split_rules::split_rule.dart::_$SplitRule" <|-- "project_bs::runtime_models::bill::split_rules::split_rule.dart::SplitRule"

' abstract class "project_bs::runtime_models::bill::split_rules::split_rule.dart::$SplitRuleCopyWith" {
'     +$Res call()
' }

' class "project_bs::runtime_models::bill::split_rules::split_rule.dart::_$SplitRuleCopyWithImpl" {
'     -$Val _value
'     -$Res Function($Val) _then
'     +$Res call()
' }

' "project_bs::runtime_models::bill::split_rules::split_rule.dart::_$SplitRuleCopyWithImpl" o-- "null::$Res Function($Val)"
' "project_bs::runtime_models::bill::split_rules::split_rule.dart::$SplitRuleCopyWith" <|-- "project_bs::runtime_models::bill::split_rules::split_rule.dart::_$SplitRuleCopyWithImpl"

' abstract class "project_bs::runtime_models::bill::split_rules::split_rule.dart::_$$SplitRuleImplCopyWith" {
'     +$Res call()
' }

' "project_bs::runtime_models::bill::split_rules::split_rule.dart::$SplitRuleCopyWith" <|-- "project_bs::runtime_models::bill::split_rules::split_rule.dart::_$$SplitRuleImplCopyWith"

' class "project_bs::runtime_models::bill::split_rules::split_rule.dart::__$$SplitRuleImplCopyWithImpl" {
'     +$Res call()
' }

' "project_bs::runtime_models::bill::split_rules::split_rule.dart::_$SplitRuleCopyWithImpl" <|-- "project_bs::runtime_models::bill::split_rules::split_rule.dart::__$$SplitRuleImplCopyWithImpl"
' "project_bs::runtime_models::bill::split_rules::split_rule.dart::_$$SplitRuleImplCopyWith" <|-- "project_bs::runtime_models::bill::split_rules::split_rule.dart::__$$SplitRuleImplCopyWithImpl"

' class "project_bs::runtime_models::bill::split_rules::split_rule.dart::_$SplitRuleImpl" {
'     +int type
'     +int hashCode
'     +_$$SplitRuleImplCopyWith<_$SplitRuleImpl> copyWith
'     +String toString()
'     +bool ==()
'     +Map<String, dynamic> toJson()
' }

' "project_bs::runtime_models::bill::split_rules::split_rule.dart::_$SplitRuleImpl" o-- "project_bs::runtime_models::bill::split_rules::split_rule.dart::_$$SplitRuleImplCopyWith<_$SplitRuleImpl>"
' "project_bs::runtime_models::bill::split_rules::split_rule.dart::_SplitRule" <|-- "project_bs::runtime_models::bill::split_rules::split_rule.dart::_$SplitRuleImpl"

abstract class "project_bs::runtime_models::bill::split_rules::split_rule.dart::_SplitRule" {
    +int type
    ' +_$$SplitRuleImplCopyWith<_$SplitRuleImpl> copyWith
}

' "project_bs::runtime_models::bill::split_rules::split_rule.dart::_SplitRule" o-- "project_bs::runtime_models::bill::split_rules::split_rule.dart::_$$SplitRuleImplCopyWith<_$SplitRuleImpl>"
"project_bs::runtime_models::bill::split_rules::split_rule.dart::SplitRule" <|-- "project_bs::runtime_models::bill::split_rules::split_rule.dart::_SplitRule"

' abstract class "project_bs::runtime_models::bill::split_rules::split_rule.dart::_$SplitRule" {
'     +int type
'     +$SplitRuleCopyWith<SplitRule> copyWith
'     +Map<String, dynamic> toJson()
' }

' "project_bs::runtime_models::bill::split_rules::split_rule.dart::_$SplitRule" o-- "project_bs::runtime_models::bill::split_rules::split_rule.dart::$SplitRuleCopyWith<SplitRule>"

@enduml