// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAnZWRaRVzMLcz9s4TkTqcDQsd69qZyXhI',
    appId: '1:734087056867:web:12b2e3ebdce8605b3a64d6',
    messagingSenderId: '734087056867',
    projectId: 'splitit-b166b',
    authDomain: 'splitit-b166b.firebaseapp.com',
    storageBucket: 'splitit-b166b.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDgFoNIm2dinTkbua0AM_EFnf-d7oThxbA',
    appId: '1:734087056867:android:46ae06459eb8ea273a64d6',
    messagingSenderId: '734087056867',
    projectId: 'splitit-b166b',
    storageBucket: 'splitit-b166b.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDA6Ks-zUDs9NJAdtOW2WmENZ74kXoufHY',
    appId: '1:734087056867:ios:68919c4e5ca63b873a64d6',
    messagingSenderId: '734087056867',
    projectId: 'splitit-b166b',
    storageBucket: 'splitit-b166b.appspot.com',
    iosClientId: '734087056867-nnv9sre08s1tba66t0jhpf0bg20m4r87.apps.googleusercontent.com',
    iosBundleId: 'com.example.projectBs',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDA6Ks-zUDs9NJAdtOW2WmENZ74kXoufHY',
    appId: '1:734087056867:ios:818cf30e3ef8dfa53a64d6',
    messagingSenderId: '734087056867',
    projectId: 'splitit-b166b',
    storageBucket: 'splitit-b166b.appspot.com',
    iosClientId: '734087056867-f26pame5cce68sa8ubu18036bogk8t0t.apps.googleusercontent.com',
    iosBundleId: 'com.example.projectBs.RunnerTests',
  );
}
